language: julia

os:
  - linux

addons:
  apt:
    packages:
      - graphviz

julia:
  - 1.0

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
# - julia -e 'using Pkg; cd(Pkg.dir("SemanticModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'using Pkg; cd(Pkg.dir("SemanticModels")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    #- stage: "Testing"
    #  script:
    #    - travis_wait 30 julia --project -e 'using Pkg; Pkg.build(); Pkg.test("SemanticModels")'
    - stage: "Documentation"
      script:
        - julia --project -e 'using Pkg; Pkg.instantiate();'
        - julia --project doc/make.jl
